username: auto763e90_pef_storage
domain: flodev.net
password: Aa@12345
oauth2: https://oauth2-api.k8s.flodev.net
#storageUrl: https://storage.k8s.flodev.net
app_id: d944424393cf309e125cbfaf0e70f1ba
device_uid: 1a05ded1-b08d-4a27-a5ab-2021d08d7919
